params:
  color: SeaGreen           # Any color in CSS syntax
  width: 48rem          # Any length in CSS syntax / leave empty to span page
  divider: \a0          # Any string in CSS syntax / leave empty for no divider
  footer: >-            # HTML spaces (&#32;) are needed before HTML elements
    All Cats Are Beautiful
  rss: To subscribe to this RSS feed, copy its address and paste it into your
    favorite feed reader.
  noClasses: true       # Set to the same value as markup.highlight.noClasses
  headingoffset: 0      # Change heading levels when rendering markdown
  linkicons: hover      # Set to hover or true to add a link icon to headings
  summaries: false      # Set to true to show summaries of posts on homepage
  schema: false         # Set to true to add Schema.org metadata
  opengraph: false      # Set to true to add Open Graph metadata
  twittercards: true   # Set to true to add Twitter Cards metadata
  utterances:
    repo:               # Set to Utterances repo URL to add Utterances comments
    issueterm:          # Leave empty for the default blog post to issue mapping
    theme:              # Leave empty to use the adaptive Utterances dark theme
  netlify:
    honeypot: false     # Set to true to add honeypot field in contact form
    recaptcha: false    # Set to true to add recaptcha challenge in contact form
  css: custom.css               # Uncomment to add custom CSS from the assets directory
  #   - bar.css
  # js:                 # Uncomment to add custom JS from the assets directory
  #   - js/foo.js
  #   - bar.js



mediaTypes:
  font/woff2:
    suffixes:
      - woff2
